# Generated by Django 4.0.3 on 2022-04-02 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='angel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inversion',
            name='angel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.angel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inversion',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='angel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.angel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='angel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.angel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pioneer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='pioneer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.pioneer'),
            preserve_default=False,
        ),
    ]
