# Generated by Django 4.0.3 on 2022-04-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pioneer',
            name='user',
        ),
        migrations.AlterField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(limit_choices_to=mainapp.models.limit_to_investors, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='investor',
            field=models.ForeignKey(limit_choices_to=mainapp.models.limit_to_investors, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='investor',
            field=models.ForeignKey(limit_choices_to=mainapp.models.limit_to_investors, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='pioneer',
            field=models.ForeignKey(limit_choices_to=mainapp.models.limit_to_pioneers, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Investor',
        ),
        migrations.DeleteModel(
            name='Pioneer',
        ),
    ]
