# Generated by Django 4.0.3 on 2022-04-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_angel_user_inversion_angel_inversion_project_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inversion',
            new_name='Investment',
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
