# Generated by Django 4.0.3 on 2022-04-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_pioneer_user_alter_investment_investor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hasEnded',
            field=models.BooleanField(default=False),
        ),
    ]
