# Generated by Django 4.0.3 on 2022-04-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_inversion_investment_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
    ]
